version: '3' # docker-compose 버전 지정

services:  # docker-compose의 경우 docker 컨테이너로 수행될 서비스들은 services 하위에 기술
  react:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: react
        ports:
            - 80:80
